# DB、ストレージ系
dynamodb:
  region: <Your AWS Region ex:us-east-1>
  url: <Your DynamoDB Local URL ex:http://localhost:10000>
s3:
  region: <Your AWS Region ex:us-east-1>
  bucket: <Your S3 Bucket Name ex:your-backend-dev>

# 通知
sqs:
  region: <Your AWS Region ex:us-east-1>
  create-image-queue-url: <Your SQS Create Image Queue URL ex:https://sqs.us-east-1.amazonaws.com/xxx/xxx>
  process-image-queue-url: <Your SQS Process Image Queue URL ex:https://sqs.us-east-1.amazonaws.com/xxx/xxx>

# フロントエンド連携
cors:
  origins: <Your Frontend Origin ex:https://localhost:3001>
cdn:
  active: <CDN Active Flag ex:false>
  url: <Your CDN URL ex:https://dev.yourcdn.net>

# NodeJS設定
nodeJs:
  path: <Your Node Scripts Absoluet Path ex:/Users/{username}/angel-sandbox/node-scripts>

# ログ
logging:
  level:
    root: <Logging Level ex:INFO>
    org.springframework.web: <Logging Level ex:INFO>
  pattern:
    dateformat: <Date Format ex:yyyy-MM-dd HH:mm:ss.SSS,Asia/Tokyo>

# AWS認証
spring:
  cloud:
    aws:
      credentials:
        profile:
          name: <Your AWS Profile Name ex:your_dev_profile>