openapi: 3.0.0

info:
  title: IllustAI OpenApi
  description: ""
  version: 1.0.0
  contact: {}

tags:
  - name: users
    description: ユーザーに関する事項
  - name: works
    description: 作品に関する事項

servers:
  - url: https://localhost:8080
    description: Local HTTPS server
  - url: http://localhost:8080
    description: Local HTTP server

paths:
  # users
  /me:
    $ref: "./paths/users.yaml#/UsersMe"

  /users/{customUserId}:
    $ref: "./paths/users.yaml#/UsersById"

  /users/activity/search:
    $ref: "./paths/users.yaml#/UsersActivitySearch"

  /users/liked:
    $ref: "./paths/users.yaml#/UsersLiked"

  /users/liked/{workId}:
    $ref: "./paths/users.yaml#/UsersLikedByWorkId"

  /users/viewed:
    $ref: "./paths/users.yaml#/UsersViewed"

  /users/viewed/{workId}:
    $ref: "./paths/users.yaml#/UsersViewedByWorkId"

  # works
  /works/create:
    $ref: "./paths/works.yaml#/WorksCreate"

  /works/{workId}:
    $ref: "./paths/works.yaml#/WorksById"

  /works/{workId}/metaDatas:
    $ref: "./paths/works.yaml#/WorksMetaDatasById"

  /works/searchByTags:
    $ref: "./paths/works.yaml#/WorksSearchByTags"

  /works/tags:
    $ref: "./paths/works.yaml#/WorksTags"

  /works/tags/{tagId}:
    $ref: "./paths/works.yaml#/WorksTagsById"

components:
  securitySchemes:
    FirebaseAuth:
      type: apiKey
      name: x-access-token
      in: header
      description: Cognitoで発行したJWT

  schemas:
    # users  
    ApiUser:
      $ref: "./components/schemas/users.yaml#/ApiUser"

    ApiLiked:
      $ref: "./components/schemas/users.yaml#/ApiLiked"

    ApiViewed:
      $ref: "./components/schemas/users.yaml#/ApiViewed"

    ApiUsersActivity:
      $ref: "./components/schemas/users.yaml#/ApiUsersActivity"

    ApiUsersActivitySearch:
      $ref: "./components/schemas/users.yaml#/ApiUsersActivitySearch"

    # works
    ApiWorkWithTag:
      $ref: "./components/schemas/works.yaml#/ApiWorkWithTag"

    ApiWork:
      $ref: "./components/schemas/works.yaml#/ApiWork"

    ApiWorkSearchByTags:
      $ref: "./components/schemas/works.yaml#/ApiWorkSearchByTags"

    ApiWorksWithSearchResult:
      $ref: "./components/schemas/works.yaml#/ApiWorksWithSearchResult"

    ApiTag:
      $ref: "./components/schemas/works.yaml#/ApiTag"

    # errors
    ApiErrorStatus:
      $ref: "./components/schemas/errors.yaml#/ApiErrorStatus"

  responses:
    # works
    WorksRegisterResponse:
      $ref: "./components/responses/works.yaml#/WorksRegisterResponse"

    WorksSearchResponse:
      $ref: "./components/responses/works.yaml#/WorksSearchResponse"

    WorksIdResponse:
      $ref: "./components/responses/works.yaml#/WorksIdResponse"

    WorksIdGetResponse:
      $ref: "./components/responses/works.yaml#/WorksIdGetResponse"

    WorksTagsResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsResponse"

    WorksTagsGetResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsGetResponse"

    # errors
    BadRequestResponse:
      $ref: "./components/responses/errors.yaml#/BadRequestResponse"

    UnauthorizedResponse:
      $ref: "./components/responses/errors.yaml#/UnauthorizedResponse"
