openapi: 3.0.0

info:
  title: IllustAI OpenApi
  description: ""
  version: 1.0.0
  contact: {}

tags:
  - name: users
    description: ユーザーに関する事項
  - name: works
    description: 作品に関する事項

servers:
  - url: https://localhost:8080
    description: Local HTTPS server
  - url: http://localhost:8080
    description: Local HTTP server

paths:
  # users
  /me:
    $ref: "./paths/users.yaml#/UsersMe"

  /public/users/{customUserId}:
    $ref: "./paths/users.yaml#/PublicUsersById"

  /users/{customUserId}:
    $ref: "./paths/users.yaml#/UsersById"

  /users/{customUserId}/works:
    $ref: "./paths/users.yaml#/UsersWorks"

  /users/follow/{userId}:
    $ref: "./paths/users.yaml#/UsersFollow"

  /users/follow/{customUserId}:
    $ref: "./paths/users.yaml#/UsersFollowById"

  /users/follower/{customUserId}:
    $ref: "./paths/users.yaml#/UsersFollowerById"

  /users/liked/{workId}:
    $ref: "./paths/users.yaml#/UsersLikedByWorkId"

  # works
  /public/works:
    $ref: "./paths/works.yaml#/PublicWorks"
  
  /public/works/{workId}:
    $ref: "./paths/works.yaml#/PublicWorksById"

  /public/works/tags/{tag}:
    $ref: "./paths/works.yaml#/PublicWorksTags"

  /works:
    $ref: "./paths/works.yaml#/Works"

  /works/create:
    $ref: "./paths/works.yaml#/WorksCreate"

  /works/{workId}:
    $ref: "./paths/works.yaml#/WorksById"

  # billings
  /billings/create-checkout-session:
    $ref: "./paths/billings.yaml#/BillingsCreateCheckoutSession"

  /billings/create-portal-session:
    $ref: "./paths/billings.yaml#/BillingsCreatePortalSession"

components:
  securitySchemes:
    FirebaseAuth:
      type: apiKey
      name: x-access-token
      in: header
      description: Cognitoで発行したJWT

  schemas:
    # users  
    ApiUser:
      $ref: "./components/schemas/users.yaml#/ApiUser"

    ApiLiked:
      $ref: "./components/schemas/users.yaml#/ApiLiked"

    # works
    ApiWorkWithTag:
      $ref: "./components/schemas/works.yaml#/ApiWorkWithTag"

    ApiWork:
      $ref: "./components/schemas/works.yaml#/ApiWork"

    ApiTag:
      $ref: "./components/schemas/works.yaml#/ApiTag"

    # errors
    ApiErrorStatus:
      $ref: "./components/schemas/errors.yaml#/ApiErrorStatus"

  responses:
    # works
    WorksRegisterResponse:
      $ref: "./components/responses/works.yaml#/WorksRegisterResponse"

    WorksIdResponse:
      $ref: "./components/responses/works.yaml#/WorksIdResponse"

    WorksTagsResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsResponse"

    WorksTagsGetResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsGetResponse"

    # errors
    BadRequestResponse:
      $ref: "./components/responses/errors.yaml#/BadRequestResponse"

    UnauthorizedResponse:
      $ref: "./components/responses/errors.yaml#/UnauthorizedResponse"
