openapi: 3.0.0

info:
  title: IllustAI OpenApi
  description: ""
  version: 1.0.0
  contact: {}

tags:
  - name: users
    description: ユーザーに関する事項
  - name: myusers
    description: 自分のユーザーに関する事項
  - name: publicusers
    description: 公開ユーザーに関する事項
  - name: works
    description: 作品に関する事項
  - name: myworks
    description: 自分の作品に関する事項
  - name: publicworks
    description: 公開作品に関する事項

servers:
  - url: https://localhost:8080
    description: Local HTTPS server
  - url: http://localhost:8080
    description: Local HTTP server

paths:
  # myusers
  /me:
    $ref: "./paths/myusers.yaml#/UsersMe"

  # users
  /users/{customUserId}:
    $ref: "./paths/users.yaml#/UsersById"

  /users/follow/{customUserId}:
    $ref: "./paths/users.yaml#/UsersFollowById"

  /users/follower/{customUserId}:
    $ref: "./paths/users.yaml#/UsersFollowerById"

  /users/follow/{userId}:
    $ref: "./paths/users.yaml#/UsersFollow"

  /users/liked/{workId}:
    $ref: "./paths/users.yaml#/UsersLikedByWorkId"

  # publicusers
  /public/users/{customUserId}:
    $ref: "./paths/publicusers.yaml#/PublicUsersById"

  /public/users/follow/{customUserId}:
    $ref: "./paths/publicusers.yaml#/PublicUsersFollowById"

  /public/users/follower/{customUserId}:
    $ref: "./paths/publicusers.yaml#/PublicUsersFollowerById"

  # myworks
  /myworks/create:
    $ref: "./paths/myworks.yaml#/MyWorksCreate"

  /myworks/{workId}:
    $ref: "./paths/myworks.yaml#/MyWorksById"

  # works
  /works:
    $ref: "./paths/works.yaml#/Works"
  
  /works/{workId}:
    $ref: "./paths/works.yaml#/WorksById"

  /works/user/{customUserId}:
    $ref: "./paths/works.yaml#/WorksUsers"

  # publicworks
  /public/works:
    $ref: "./paths/publicworks.yaml#/PublicWorks"
  
  /public/works/{workId}:
    $ref: "./paths/publicworks.yaml#/PublicWorksById"
  
  /public/works/user/{customUserId}:
    $ref: "./paths/publicworks.yaml#/PublicWorksUsers"

  /public/works/tags/{tag}:
    $ref: "./paths/publicworks.yaml#/PublicWorksTags"

  # billings
  /billings/create-checkout-session:
    $ref: "./paths/billings.yaml#/BillingsCreateCheckoutSession"

  /billings/create-portal-session:
    $ref: "./paths/billings.yaml#/BillingsCreatePortalSession"

components:
  securitySchemes:
    FirebaseAuth:
      type: apiKey
      name: x-access-token
      in: header
      description: Cognitoで発行したJWT

  schemas:
    # users  
    ApiUser:
      $ref: "./components/schemas/users.yaml#/ApiUser"

    ApiLiked:
      $ref: "./components/schemas/users.yaml#/ApiLiked"

    # works
    ApiWorkWithTag:
      $ref: "./components/schemas/works.yaml#/ApiWorkWithTag"

    ApiWork:
      $ref: "./components/schemas/works.yaml#/ApiWork"

    ApiTag:
      $ref: "./components/schemas/works.yaml#/ApiTag"

    # errors
    ApiErrorStatus:
      $ref: "./components/schemas/errors.yaml#/ApiErrorStatus"

  responses:
    # works
    WorksRegisterResponse:
      $ref: "./components/responses/works.yaml#/WorksRegisterResponse"

    WorksIdResponse:
      $ref: "./components/responses/works.yaml#/WorksIdResponse"

    WorksTagsResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsResponse"

    WorksTagsGetResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsGetResponse"

    # errors
    BadRequestResponse:
      $ref: "./components/responses/errors.yaml#/BadRequestResponse"

    UnauthorizedResponse:
      $ref: "./components/responses/errors.yaml#/UnauthorizedResponse"
